name: CI 

on: push

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Run Ruff linter
      run: |
        ruff waveform_editor

  pytest:
    runs-on: ubuntu-latest
    needs: linting
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Run tests
      run: |
        pytest waveform_editor

  docs:
    runs-on: ubuntu-latest
    needs: pytest  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[doc]

    - name: Build documentation
      run: |
        make -C docs html
      working-directory: docs

    - name: Upload docs artifact
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/_build/html/
