name: CI 

on: push

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[linting]

    - name: Run Ruff linter
      run: |
        ruff check --output-format=github waveform_editor

  pytest:
    runs-on: ubuntu-latest
    needs: linting
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]

    - name: Run tests
      run: |
        python -m pytest -n=auto --cov=vtkggdtools --cov-report=term-missing --cov-report=html --junit-xml=junit.xml

  docs:
    runs-on: ubuntu-latest
    needs: pytest  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[docs]

    - name: Build documentation
      run: |
        make -C docs html

    - name: Upload docs artifact
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/_build/html/
